#pragma once

#define GAME_BUILD_TYPE_DEBUG		(!NDEBUG)
#define GAME_BUILD_TYPE_RELEASE		(NDEBUG > 0)

#define GAME_PLATFORM_EMSCRIPTEN	(__EMSCRIPTEN__ > 0)
#define GAME_PLATFORM_WINDOWS		((_WIN32 > 0) && !GAME_PLATFORM_EMSCRIPTEN)
#define GAME_PLATFORM_LINUX			((__unix__ > 0) && !GAME_PLATFORM_EMSCRIPTEN)
